platform: linux
image_resource: ((cf_tasks_image_resource))

inputs:
# - The repo that contains run-release-script.sh.
- name: log-cache-ci

outputs:
# - The directory where the result of running the script is copied. This will
#   include all the files from the input bosh release.
- name: golang-blobs

params:
  # - Required
  # - The version of Go to bump to.
  VERSION:

run:
  path: log-cache-ci/tasks/download-golang/task
