---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: loggregator/base

inputs:
- name: log-cache-ci # - This repo
- name: source-repo    # - The Go package to test

run:
  path: log-cache-ci/tasks/go-test-with-latest-packages/task

params:
  # - Required
  # - The import path of the package to test.
  IMPORT_PATH:
