product-name: observability-store
network-properties:
  network:
    name: optimus-pas-subnet
  other_availability_zones:
    - name: us-central1-a
    - name: us-central1-b
    - name: us-central1-c
  singleton_availability_zone:
    name: us-central1-a
