image_resource:
  type: docker-image
  source:
    repository: logcache/base
platform: linux

inputs:
- name: log-cache-ci
- name: log-cache-release-backport
- name: log-cache-release-develop
- name: log-cache-release-version-backport

outputs:
- name: github-release
- name: log-cache-release-backport-modified
- name: log-cache-release-develop-modified

run:
  path: log-cache-ci/tasks/create-final-backport-release/task

params:
  S3_ACCESS_KEY:
  S3_SECRET_KEY:
  BACKPORT_BRANCH:
