---
platform: linux
image_resource: ((cf_tasks_image_resource))

inputs:
- name: log-cache-ci # - This repo
- name: release-repo

outputs:
- name: committed-repo

run:
  path: ../log-cache-ci/tasks/commit-with-shortlog/task
  dir: committed-repo

params:
  # Required. The paths to commit.
  PATHS:
