---
platform: linux

inputs:
  - name: environment
  - name: deployment-tools
  - name: log-cache-ci
  - name: tile-config
    optional: true
  - name: tile-version
  - name: metric-store-dev-release
  - name: metric-store-release
  - name: oss-metric-store-release

outputs:
  - name: baked-tile
  - name: new-tile-version

params:
  OPSMAN_USER:
  OPSMAN_PASSWORD:
  TILE_NAME: app-metric-store
  STEMCELL_URL:
  STEMCELL_SHA:
  PRODUCT_CONFIG_PATH:

run:
  path: log-cache-ci/tasks/bake_and_install/task
